CREATE TABLE IF NOT EXISTS TRACKER
(
    tracker_playerUuid VARCHAR(36) NOT NULL PRIMARY KEY,
    tracker_accepted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS RULES
(
    rule_id INTEGER NOT NULL PRIMARY KEY NOT NULL,
    rule_message TEXT NOT NULL,
    rule_dateAdded VARCHAR(50) NOT NULL
);